################################# Default configuration ###################
baseURL = "/"
title = "Curso-R | Descomplicando a Ciência de Dados"
theme = "meghna-hugo"
defaultContentLanguage = "pt"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "curso-r-com"
# disable language
disableLanguages = ["en"]
publishDir = "docs"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.css]]
link = "css/hex.css"
[[params.plugins.css]]
link = "css/linktree.css"


# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "https://platform.illow.io/banner.js?siteId=962b4071-1b48-4756-8b80-68101acc70df"

################### Portuguese Navigation ########################
[[Languages.pt.menu.main]]
name = "Sobre"
pre = "#"
url = "about"
weight = 1

[[Languages.pt.menu.main]]
name = "Consultoria"
pre = ""
url = "http://www.rseis.com.br"
weight = 2

[[Languages.pt.menu.main]]
name = "YouTube"
pre = "#"
url = "canal_yt"
weight = 3

[[Languages.pt.menu.main]]
name = "Equipe"
pre = "#"
url = "team"
weight = 5

[[Languages.pt.menu.main]]
name = "Fórum de dúvidas"
pre = "#"
url = "forum"
weight = 6

[[Languages.pt.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 7

[[Languages.pt.menu.main]]
name = "Material"
pre = ""
url = "/material"
weight = 8

[[Languages.pt.menu.main]]
name = "Pacotes"
pre = ""
url = "/pacotes"
weight = 9

[[Languages.pt.menu.main]]
name = "Contato"
pre = "#"
url = "contact"
weight = 10

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
pre = "#"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "store"
pre = "#"
url = "store"
weight = 2

[[Languages.en.menu.main]]
name = "services"
pre = "#"
url = "services"
weight = 3

[[Languages.en.menu.main]]
name = "Courses"
pre = "#"
url = "portfolio"
weight = 4

[[Languages.en.menu.main]]
name = "Team"
pre = "#"
url = "team"
weight = 5

[[Languages.en.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 6

[[Languages.en.menu.main]]
name = "Material"
pre = "#"
url = "blog"
weight = 7

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 8

[[Languages.en.menu.main]]
name = "Book"
pre = ""
url = "https://livro.curso-r.com/"
weight = 9

############################# Default Parameters ##########################
[params]
logo = "images/logo_col_branco.webp"
# Meta data
description = "A Curso-R é uma empresa de cursos de programação em R e consultoria em ciência de dados. Nossa missão é descomplicar a ciência de dados para a comunidade."
author = "Curso-R"
# Google Analytics
google_analytics_id = "UA-87272102-2" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo_col_branco.webp"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.webp"

############################# social icons ##########################
[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCTXuqtCYxPVEehq6fJY9GkA"
name = "YouTube"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/curso_r"
name = "Twitter"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/cursoo_r/"
name = "Instagram"

[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/cursodeR/"
name = "Facebook"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://br.linkedin.com/company/curso-r"
name = "Linkedin"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/curso-r"
name = "Github"



############################# links ############## ##########################
[[params.links]]
icon = "ti-shopping-cart" # themify icon pack : https://themify.me/themify-icons
link = "https://loja.curso-r.com/"
name = "Loja"

[[params.links]]
icon = "ti-write" # themify icon pack : https://themify.me/themify-icons
link = "https://blog.curso-r.com/"
name = "Blog"

[[params.links]]
icon = "ti-comment" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/orgs/curso-r/discussions"
name = "Fórum de dúvidas"

[[params.links]]
icon = "ti-book" # themify icon pack : https://themify.me/themify-icons
link = "https://livro.curso-r.com/"
name = "R para Ciência de Dados"

[[params.links]]
icon = "ti-book" # themify icon pack : https://themify.me/themify-icons
link = "https://programando-em-shiny.curso-r.com/"
name = "Programando em Shiny"

################################ Portuguese Language ########################
[Languages.pt]
languageName = "Pt"
languageCode = "pt-br"
contentDir = "content/portuguese"
weight = 1
home = "Home"
copyright = "&copy; Copyright Curso-R 2024. Todos os direitos reservados."
ref = "Tema por [Themefisher](https://themefisher.com). Site feito em [Hugo](https://gohugo.io/) com o pacote [{blogdown}](https://bookdown.org/yihui/blogdown/)."


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; Curso-R 2024"
ref = "Theme by [Themefisher](https://themefisher.com). Site built with [Hugo](https://gethugothemes.com) and the package [{blogdown}](https://bookdown.org/yihui/blogdown/)."

